# Generated by Django 2.2.3 on 2020-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(max_length=25)),
                ('territory', models.CharField(max_length=10)),
                ('warehouse_stock', models.IntegerField()),
                ('store_stock', models.IntegerField()),
                ('transit_stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
    ]
