# Generated by Django 2.2.3 on 2020-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='price',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
