# Generated by Django 2.2.3 on 2020-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0002_auto_20201214_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='price',
            field=models.FloatField(),
        ),
    ]
